/**********************************************************************
 *
 * Module		: HC-SR04 Ultrasonic Sensor
 *
 * File Name 	: HC-SR04.c
 *
 * Description	: The source file for HC-SR04 Ultrasonic Sensor
 *
 * Author		: Mohamed Sherif
 *
 ***********************************************************************/

#include "HC-SR04.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

/*******************************************************************************
 *                      Global variable                                        *
 *******************************************************************************/
uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

/*******************************************************************************
 *                        Configuration                                        *
 *******************************************************************************/
Icu_ConfigType Icu_Config = {F_CPU_8,RISING};

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description:
 * 	1.Initialize the ICU driver as required.
 * 	2.Setup the ICU call back function.
 * 	3.Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	/*Initialize the ICU driver as required*/
	Icu_init(&Icu_Config);

	/*Setup the ICU call back function*/
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	/* Setup the direction for the trigger pin as output pin through the GPIO driver*/
	GPIO_setupPinDirection(PORTB_ID,PIN5_ID,PIN_OUTPUT);
}

/*
 *Description:
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);

	_delay_us(10);

	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);
}

/*
 * Description
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;

	/* Send the trigger pulse by using Ultrasonic_Trigger function */
	Ultrasonic_Trigger();

	/* Start the measurements by the ICU from this moment */



	distance=g_timeHigh*0.0173;

	return distance;
}

/*
 * Description:
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;

		Icu_clearTimerValue();
	}
}
